# coding: utf-8

"""
    Coinmarketcap API Swagger Implementation

    Define coinmarketcap's api in swagger 2.0 openapi standard  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import CmcClient
from CmcClient.models.inline_response_default import InlineResponseDefault  # noqa: E501
from CmcClient.rest import ApiException


class TestInlineResponseDefault(unittest.TestCase):
    """InlineResponseDefault unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponseDefault(self):
        """Test InlineResponseDefault"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CmcClient.models.inline_response_default.InlineResponseDefault()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
