# coding: utf-8

"""
    Coinmarketcap API Swagger Implementation

    Define coinmarketcap's api in swagger 2.0 openapi standard  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import CmcClient
from CmcClient.models.cryptocurrency_info import CryptocurrencyInfo  # noqa: E501
from CmcClient.rest import ApiException


class TestCryptocurrencyInfo(unittest.TestCase):
    """CryptocurrencyInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCryptocurrencyInfo(self):
        """Test CryptocurrencyInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CmcClient.models.cryptocurrency_info.CryptocurrencyInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
