# coding: utf-8

"""
    Coinmarketcap API Swagger Implementation

    Define coinmarketcap's api in swagger 2.0 openapi standard  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import CmcClient
from CmcClient.models.inline_response_default1 import InlineResponseDefault1  # noqa: E501
from CmcClient.rest import ApiException


class TestInlineResponseDefault1(unittest.TestCase):
    """InlineResponseDefault1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponseDefault1(self):
        """Test InlineResponseDefault1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CmcClient.models.inline_response_default1.InlineResponseDefault1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
