# coding: utf-8

"""
    Coinmarketcap API Swagger Implementation

    Define coinmarketcap's api in swagger 2.0 openapi standard  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import CmcClient
from CmcClient.models.global_metrics_quotes_latest import GlobalMetricsQuotesLatest  # noqa: E501
from CmcClient.rest import ApiException


class TestGlobalMetricsQuotesLatest(unittest.TestCase):
    """GlobalMetricsQuotesLatest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGlobalMetricsQuotesLatest(self):
        """Test GlobalMetricsQuotesLatest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CmcClient.models.global_metrics_quotes_latest.GlobalMetricsQuotesLatest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
