# coding: utf-8

# flake8: noqa
"""
    Coinmarketcap API Swagger Implementation

    Define coinmarketcap's api in swagger 2.0 openapi standard  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from CmcClient.models.cryptocurrency_info import CryptocurrencyInfo
from CmcClient.models.cryptocurrency_info_urls import CryptocurrencyInfoUrls
from CmcClient.models.cryptocurrency_listings import CryptocurrencyListings
from CmcClient.models.cryptocurrency_map import CryptocurrencyMap
from CmcClient.models.global_metrics_historical_quote import GlobalMetricsHistoricalQuote
from CmcClient.models.global_metrics_quote import GlobalMetricsQuote
from CmcClient.models.global_metrics_quotes_historical import GlobalMetricsQuotesHistorical
from CmcClient.models.global_metrics_quotes_latest import GlobalMetricsQuotesLatest
from CmcClient.models.inline_response200 import InlineResponse200
from CmcClient.models.inline_response2001 import InlineResponse2001
from CmcClient.models.inline_response2002 import InlineResponse2002
from CmcClient.models.inline_response2003 import InlineResponse2003
from CmcClient.models.inline_response2004 import InlineResponse2004
from CmcClient.models.inline_response2004_data import InlineResponse2004Data
from CmcClient.models.inline_response2005 import InlineResponse2005
from CmcClient.models.inline_response2006 import InlineResponse2006
from CmcClient.models.inline_response2007 import InlineResponse2007
from CmcClient.models.inline_response2008 import InlineResponse2008
from CmcClient.models.inline_response2009 import InlineResponse2009
from CmcClient.models.inline_response_default import InlineResponseDefault
from CmcClient.models.inline_response_default1 import InlineResponseDefault1
from CmcClient.models.platform import Platform
from CmcClient.models.quote import Quote
from CmcClient.models.status import Status
