# coding: utf-8

"""
    Coinmarketcap API Swagger Implementation

    Define coinmarketcap's api in swagger 2.0 openapi standard  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from CmcClient.models.global_metrics_historical_quote import GlobalMetricsHistoricalQuote  # noqa: F401,E501


class GlobalMetricsQuotesHistorical(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'timestamp': 'datetime',
        'btc_dominance': 'float',
        'quote': 'dict(str, GlobalMetricsHistoricalQuote)'
    }

    attribute_map = {
        'timestamp': 'timestamp',
        'btc_dominance': 'btc_dominance',
        'quote': 'quote'
    }

    def __init__(self, timestamp=None, btc_dominance=None, quote=None):  # noqa: E501
        """GlobalMetricsQuotesHistorical - a model defined in Swagger"""  # noqa: E501

        self._timestamp = None
        self._btc_dominance = None
        self._quote = None
        self.discriminator = None

        if timestamp is not None:
            self.timestamp = timestamp
        if btc_dominance is not None:
            self.btc_dominance = btc_dominance
        if quote is not None:
            self.quote = quote

    @property
    def timestamp(self):
        """Gets the timestamp of this GlobalMetricsQuotesHistorical.  # noqa: E501


        :return: The timestamp of this GlobalMetricsQuotesHistorical.  # noqa: E501
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this GlobalMetricsQuotesHistorical.


        :param timestamp: The timestamp of this GlobalMetricsQuotesHistorical.  # noqa: E501
        :type: datetime
        """

        self._timestamp = timestamp

    @property
    def btc_dominance(self):
        """Gets the btc_dominance of this GlobalMetricsQuotesHistorical.  # noqa: E501


        :return: The btc_dominance of this GlobalMetricsQuotesHistorical.  # noqa: E501
        :rtype: float
        """
        return self._btc_dominance

    @btc_dominance.setter
    def btc_dominance(self, btc_dominance):
        """Sets the btc_dominance of this GlobalMetricsQuotesHistorical.


        :param btc_dominance: The btc_dominance of this GlobalMetricsQuotesHistorical.  # noqa: E501
        :type: float
        """

        self._btc_dominance = btc_dominance

    @property
    def quote(self):
        """Gets the quote of this GlobalMetricsQuotesHistorical.  # noqa: E501


        :return: The quote of this GlobalMetricsQuotesHistorical.  # noqa: E501
        :rtype: dict(str, GlobalMetricsHistoricalQuote)
        """
        return self._quote

    @quote.setter
    def quote(self, quote):
        """Sets the quote of this GlobalMetricsQuotesHistorical.


        :param quote: The quote of this GlobalMetricsQuotesHistorical.  # noqa: E501
        :type: dict(str, GlobalMetricsHistoricalQuote)
        """

        self._quote = quote

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GlobalMetricsQuotesHistorical, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GlobalMetricsQuotesHistorical):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
