# coding: utf-8

"""
    Coinmarketcap API Swagger Implementation

    Define coinmarketcap's api in swagger 2.0 openapi standard  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from CmcClient.models.global_metrics_quotes_historical import GlobalMetricsQuotesHistorical  # noqa: F401,E501


class InlineResponse2004Data(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'quote': 'list[GlobalMetricsQuotesHistorical]'
    }

    attribute_map = {
        'quote': 'quote'
    }

    def __init__(self, quote=None):  # noqa: E501
        """InlineResponse2004Data - a model defined in Swagger"""  # noqa: E501

        self._quote = None
        self.discriminator = None

        if quote is not None:
            self.quote = quote

    @property
    def quote(self):
        """Gets the quote of this InlineResponse2004Data.  # noqa: E501


        :return: The quote of this InlineResponse2004Data.  # noqa: E501
        :rtype: list[GlobalMetricsQuotesHistorical]
        """
        return self._quote

    @quote.setter
    def quote(self, quote):
        """Sets the quote of this InlineResponse2004Data.


        :param quote: The quote of this InlineResponse2004Data.  # noqa: E501
        :type: list[GlobalMetricsQuotesHistorical]
        """

        self._quote = quote

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2004Data, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2004Data):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
