# coding: utf-8

"""
    Coinmarketcap API Swagger Implementation

    Define coinmarketcap's api in swagger 2.0 openapi standard  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Platform(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'symbol': 'str',
        'slug': 'str',
        'token_address': 'str'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'symbol': 'symbol',
        'slug': 'slug',
        'token_address': 'token_address'
    }

    def __init__(self, id=None, name=None, symbol=None, slug=None, token_address=None):  # noqa: E501
        """Platform - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._name = None
        self._symbol = None
        self._slug = None
        self._token_address = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if symbol is not None:
            self.symbol = symbol
        if slug is not None:
            self.slug = slug
        if token_address is not None:
            self.token_address = token_address

    @property
    def id(self):
        """Gets the id of this Platform.  # noqa: E501


        :return: The id of this Platform.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Platform.


        :param id: The id of this Platform.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this Platform.  # noqa: E501


        :return: The name of this Platform.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Platform.


        :param name: The name of this Platform.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def symbol(self):
        """Gets the symbol of this Platform.  # noqa: E501


        :return: The symbol of this Platform.  # noqa: E501
        :rtype: str
        """
        return self._symbol

    @symbol.setter
    def symbol(self, symbol):
        """Sets the symbol of this Platform.


        :param symbol: The symbol of this Platform.  # noqa: E501
        :type: str
        """

        self._symbol = symbol

    @property
    def slug(self):
        """Gets the slug of this Platform.  # noqa: E501


        :return: The slug of this Platform.  # noqa: E501
        :rtype: str
        """
        return self._slug

    @slug.setter
    def slug(self, slug):
        """Sets the slug of this Platform.


        :param slug: The slug of this Platform.  # noqa: E501
        :type: str
        """

        self._slug = slug

    @property
    def token_address(self):
        """Gets the token_address of this Platform.  # noqa: E501


        :return: The token_address of this Platform.  # noqa: E501
        :rtype: str
        """
        return self._token_address

    @token_address.setter
    def token_address(self, token_address):
        """Sets the token_address of this Platform.


        :param token_address: The token_address of this Platform.  # noqa: E501
        :type: str
        """

        self._token_address = token_address

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Platform, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Platform):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
