# coding: utf-8

"""
    Coinmarketcap API Swagger Implementation

    Define coinmarketcap's api in swagger 2.0 openapi standard  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Status(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'timestamp': 'datetime',
        'error_code': 'int',
        'error_message': 'str',
        'elapsed': 'int',
        'credit_count': 'int'
    }

    attribute_map = {
        'timestamp': 'timestamp',
        'error_code': 'error_code',
        'error_message': 'error_message',
        'elapsed': 'elapsed',
        'credit_count': 'credit_count'
    }

    def __init__(self, timestamp=None, error_code=None, error_message=None, elapsed=None, credit_count=None):  # noqa: E501
        """Status - a model defined in Swagger"""  # noqa: E501

        self._timestamp = None
        self._error_code = None
        self._error_message = None
        self._elapsed = None
        self._credit_count = None
        self.discriminator = None

        if timestamp is not None:
            self.timestamp = timestamp
        if error_code is not None:
            self.error_code = error_code
        if error_message is not None:
            self.error_message = error_message
        if elapsed is not None:
            self.elapsed = elapsed
        if credit_count is not None:
            self.credit_count = credit_count

    @property
    def timestamp(self):
        """Gets the timestamp of this Status.  # noqa: E501


        :return: The timestamp of this Status.  # noqa: E501
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this Status.


        :param timestamp: The timestamp of this Status.  # noqa: E501
        :type: datetime
        """

        self._timestamp = timestamp

    @property
    def error_code(self):
        """Gets the error_code of this Status.  # noqa: E501


        :return: The error_code of this Status.  # noqa: E501
        :rtype: int
        """
        return self._error_code

    @error_code.setter
    def error_code(self, error_code):
        """Sets the error_code of this Status.


        :param error_code: The error_code of this Status.  # noqa: E501
        :type: int
        """

        self._error_code = error_code

    @property
    def error_message(self):
        """Gets the error_message of this Status.  # noqa: E501


        :return: The error_message of this Status.  # noqa: E501
        :rtype: str
        """
        return self._error_message

    @error_message.setter
    def error_message(self, error_message):
        """Sets the error_message of this Status.


        :param error_message: The error_message of this Status.  # noqa: E501
        :type: str
        """

        self._error_message = error_message

    @property
    def elapsed(self):
        """Gets the elapsed of this Status.  # noqa: E501


        :return: The elapsed of this Status.  # noqa: E501
        :rtype: int
        """
        return self._elapsed

    @elapsed.setter
    def elapsed(self, elapsed):
        """Sets the elapsed of this Status.


        :param elapsed: The elapsed of this Status.  # noqa: E501
        :type: int
        """

        self._elapsed = elapsed

    @property
    def credit_count(self):
        """Gets the credit_count of this Status.  # noqa: E501


        :return: The credit_count of this Status.  # noqa: E501
        :rtype: int
        """
        return self._credit_count

    @credit_count.setter
    def credit_count(self, credit_count):
        """Sets the credit_count of this Status.


        :param credit_count: The credit_count of this Status.  # noqa: E501
        :type: int
        """

        self._credit_count = credit_count

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Status, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Status):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
